apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: backend
  namespace: data-plane
spec:
  selector:
    matchLabels:
      app: backend
  mtls:
    mode: STRICT #UNSET, DISABLE, PERMISSIVE, STRICT