apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: frontend
  namespace: data-plane
spec:
  selector:
    matchLabels:
      app: frontend
  mtls:
    mode: STRICT #UNSET, DISABLE, PERMISSIVE, STRICT