apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: data-plane
spec:
  host: frontend.data-plane.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL